Add CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -59,7 +59,30 @@ jobs:
       - name: Build and Start Server
         run: |
           cd server
-          docker-compose up --build
+          docker-compose up --build -d
+
+      - name: Wait for services to be ready
+        run: |
+          cd client
+          java -jar ./build/libs/client-0.0.1-SNAPSHOT.jar base >output.txt &
+          for i in {1..30}; do
+            sleep 1
+            cat output.txt | tail -n 3
+            if grep -q "Connected to server" output.txt; then
+              echo "Server connected successfully. Killing process."
+              pkill -f 'java -jar ./build/libs/client-0.0.1-SNAPSHOT.jar'
+              exit 0
+            fi
+          done
+          pkill -f 'java -jar ./build/libs/client-0.0.1-SNAPSHOT.jar'
+          if grep -q "Connected to server" output.txt; then
+            echo "Server connected successfully. Killing process."
+            exit 0
+          fi
+          echo "Server connection failed. Exiting with error."
+          ls
+          cat output.txt
+          exit 1
 
       - name: Stop services
         run: |
